appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZUe8BWL+aMh+gdFSLN3PCb8zkuMY4lN8BFUguG0FLfuMkXxp3hoT9DZbDX22GLRfvy4Cq6Ase3IgyqJ+oCfB9CQ0MMgdDH/vdivYn6P2bbLuEA7hduNExWh4UnD9oGv/xWQkXs3W7uUrGua0IHqqoyx5/+wt6bV5H1jc28EmN/rN9ohcnTn3I9g/J/wdYrXzJ+0wruXkERpnQ071a42kxUkmVxC3plLjEEQKnSqyCgPwkAbpe2nRvriYg86khKSeFOohslVcsp4B20W3eHHgUDLmjEPNr/Sb1Eo/zYBn9vZVCb6rxJaWmg0FQjK5Lb1ddc0UqxKA3A2sZo6uT4QnqErmXlSEEsXv6EPaCpaqMukE6jPXR4iH77E0HPgLP3IWJpfpYaDf28QpCXZar2Gt4jtU8rr5jOYIwhcnbSS/z74DBo/8DF3BLb70vFH1WrWWgDvqUPBhxj3GdbKhXUEPmIwpf5t28n4eluFPxDexdvAbr5mFgvEllXHMgd28sOc07Ssz9NYHeT1Tb3Argw/sFufCwGCf5e4B//eF4BFpRy5RK2GpaZStp9v8GxxRhOrkhslmD/QUItQN+yPUhIVXVjX/oLfguezgNuWWzt+V6vSmawsylZnOFGOJ3xeES3dWPX+GYEcb+yCtEh0mY3JgiUQmSlDfRwnLp1HcGOkW7Tw=}
